### PR TITLE
Adding PyScript Pentesting Guide

### PR DESCRIPTION
**Pull request by Cyber-Guy1**

### CODE REVIEW

**Comment by Cyber-Guy1** [comment]
I also added additional cheat sheets into the web-api-pentesting in addition to the new added section - PyScript Pentesting Guide -

**Comment by clem9669** [comment]
Far better 😉 

👍

**Comment by Cyber-Guy1** [comment]
Thanks 🥰

**Comment by Cyber-Guy1** [comment]
Hi @carlospolop and @clem9669 
When would you merge this new repo?

**Comment by carlospolop** [comment]
sorry mate, merging things that contain new pages unfortunately require more time and I wasn't almost available. I'm going to merge it now

**Comment by carlospolop** [comment]
You can find it in https://book.hacktricks.xyz/generic-methodologies-and-resources/python/pyscript

**Pull request merged**
