### PR TITLE
Create SAP pentesting

### PR DESCRIPTION
**Pull request by clem9669**
First commit for SAP pentesting, more to follow.

### CODE REVIEW

**Comment by carlospolop** [comment]
Amazing man! I always wanted to learn about this (but who can find time?). Fell free to upload more content

**Comment by clem9669** [comment]
Hey, 
I have been searching for how it renders and where is located under the gitbook structure but i didn't manage to found it 😞 

https://book.hacktricks.xyz/?q=SAP

Do you have any idea where it could be ? 

Thanks

**Comment by carlospolop** [comment]
Thanks actually a good question, I cannot find it in the book xD
Let me copy&paste it when I find some spare minutes with the PC

**Comment by clem9669** [comment]
Hi,
Have you investigated this issue ? 😃

**Comment by carlospolop** [comment]
Sorry mate, I completely forgot about this. Thanks for the reminding.
You can find it in https://book.hacktricks.xyz/pentesting/pentesting-sap

**Pull request merged**
