### PR TITLE
SMB: add enum4linux-ng

### PR DESCRIPTION
**Pull request by noraj**

### CODE REVIEW

**Comment by clem9669** [comment]
Hey @noraj 

Do you recommand enum4linux-ng over enum4linux ?

**Comment by noraj** [comment]
enum4linux-ng do new stuff like JSON output, ipv6, smbv2 support but seems to do less stuff than enum4linux so I'd say to use both

**Comment by clem9669** [comment]
Good to know thanks 😃

**Comment by carlospolop** [comment]
Thanks!

**Pull request merged**
