### PR TITLE
New GCP Persistence/Lateral Movement

### PR DESCRIPTION
**Pull request by rek7**

### CODE REVIEW

**Comment by rek7** [comment]
Is there any update on the status of this pull request?

**Comment by carlospolop** [comment]
Hey @rek7,
This technique is pretty interesting thanks for sharing. Quick question, could this also be used for privesc? If you can make all compute instances run arbitrary code I guess you could access their service accounts through the metadata and escalate to them, or am I missing something?

**Comment by rek7** [comment]
Yes it can be I added it to both persistence and privesc.

**Comment by carlospolop** [comment]
hey @rek7,
I finally had some time to dedicate to this!
The technique is awesome, thank you for sharing. If you find other interesting permissions keep them coming!

**Comment by rek7** [comment]
Thanks :)

**Comment by rek7** [comment]
Hey it seems like the entire cloud security section is gone, any update?

**Comment by carlospolop** [comment]
It wasn't remove, take a closer look. It was replaced for links to https://cloud.hacktricks.xyz/

**Pull request merged**
